### ISSUE TITLE
Issu with nom run build

### ISSUE THREAD

**Issue by Setirf32** [The-Stripes-NFT/nft-minting-app#6]

**Comment by An-prog-hub** [comment]
try to include 
    `"watchpack": "^2.3.1"`
in package.json.

Then run the command ``npm install`` and finally ``npm start`` the start the on localhost

**Comment by RippedFish** [comment]
Getting this error: Failed at the the_stripes_nft_dapp@1.0.0 start script 'react-scripts start'.

**Comment by martinnaj** [comment]
Please show the entire error. Thanks.

**Comment by Paandasaurus** [comment]
> the_stripes_nft_dapp@1.0.0 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\User\Desktop\nft-minting-app-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\Users\User\Desktop\nft-minting-app-main\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\User\Desktop\nft-minting-app-main\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\User\Desktop\nft-minting-app-main\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'


I get this, anyone help?

**Comment by An-prog-hub** [comment]
try doing ```npm audit```
